# This helps python to use directories/parent folders freely without using explicit absolute paths 
# in from import statements
# Build sytems - specifies which tools are required by the pip to build this package
# project saves the name and version in pip and is displayed in pip list
# where is the directory in which we have the required folders -> . = current, .. = parent, ... = grnadparent etc
# include is where we specify all the folders that have .py files that need to used as functions in other codes

# To make this work you have to run "pip install -e ." once in your terminal containing the .toml file dir, the . in the 
# end of the command stands for this directory (dir where the toml file lives)
# only need to run it once, after which python keeps a track of the files added in those dir or removed

[build-system]
requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mlops-pipeline-customer-churn-dataset"
description = "MLOps Pipeline Customer Churn Dataset"
version = "1.0.0"

[tool.setuptools.packages.find]
where = [".."]
include = ["src*", "tests*", "scripts*"]